# Generated by Django 3.0.6 on 2020-05-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=5)),
                ('credits', models.BigIntegerField()),
                ('num_of_win', models.BigIntegerField()),
                ('num_of_failure', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_area.Classes')),
            ],
        ),
        migrations.CreateModel(
            name='PlayRecords',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('play_datetime', models.DateTimeField()),
                ('result', models.CharField(max_length=200)),
                ('student_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_a', to='weiqi_area.Students', verbose_name='甲')),
                ('student_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_b', to='weiqi_area.Students', verbose_name='乙')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_datetime', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_area.Students')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weiqi_area.Teachers'),
        ),
    ]
