# Generated by Django 3.0.6 on 2020-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiqi_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='classes',
            name='classname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
