# Generated by Django 3.0.6 on 2020-05-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiqi_area', '0002_auto_20200508_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='credits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='num_of_failure',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='num_of_win',
            field=models.BigIntegerField(default=0),
        ),
    ]
