# Generated by Django 3.0.6 on 2020-05-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weiqi_area', '0003_auto_20200508_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='losing_streak',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='winning_streak',
            field=models.BigIntegerField(default=0),
        ),
    ]
